### ISSUE TITLE
Entries and assets into same Algolia index

### ISSUE THREAD

**Issue by nickdunn** [riasvdv/craft-scout#186]
I want to achieve a site search that lets me filter by:

* Page (a section)
* People (a section)
* Locations (a section)
* Documents (an asset volume)

In Algolia this means querying from a single index so that results can be ordered together. I can't achieve a good result querying multiple indices and merging them.

I have worked out how to combine my 3 sections into a single Algolia index (`$query->section(['page', 'people', 'location'])` in my `criteria`) but I can't work out how to also index assets alongside them. I tried adding two indices of the same name in my Scout config but it wants them to be unique. 

Are there generic `elementType` and `criteria` classes I could use that gives me Entries and Assets?

**Comment by timkelty** [comment]
@nickdunn Because this is not currently possible in a single criteria in Craft, it is not possible here.

It sounds like you are after the oft-requested: https://github.com/riasvdv/craft-scout/issues/69#issuecomment-616563983
Let me know if that sounds like that solution would fit your use-case. Sounds like it to me?

**Comment by nickdunn** [comment]
Aha I hadn’t spotted this thread. Yes, getElements would solve this for me!
